export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const GET_COURSES = 'GET_COURSES';
export const COURSE_ERROR = 'COURSE_ERROR';
export const SEARCH_COURSES = 'SEARCH_COURSES';
export const SELECT_COURSE = 'SELECT_COURSE';
export const UNSELECT_COURSE = 'UNSELECT_COURSE';
export const CLEAN_COURSE = 'CLEAN_COURSE';
export const GET_COURSE = 'GET_COURSE';
export const GET_SECTIONS = 'GET_SECTIONS';
export const REPLACE_PROF = 'REPLACE_PROF';
export const GET_PROFDETAILS = 'GET_PROFDETAILS';
export const UPDATE_PROFS = 'UPDATE_PROFS';

export const SET_COMPARE_COURSE = 'SET_COMPARE_COURSE';
export const CLEAN_COMPARE_COURSE = 'CLEAN_COMPARE_COURSE';

export const SELECT_SECTION = 'SELECT_SECTION';
export const UNSELECT_SECTION = 'UNSELECT_SECTION';

export const GET_PROFS = 'GET_PROFS';
export const SET_PROF = 'SET_PROF';
export const GET_COURSE_SECTIONS = 'GET_COURSE_SECTIONS';

export const GET_REVIEWS = 'GET_REVIEWS';
export const UPVOTE = 'UPVOTE';
export const DOWNVOTE = 'DOWNVOTE';
export const ADD_REVIEW = 'ADD_REVIEW';
export const REVIEW_ERROR = 'REVIEW_ERROR';
export const GET_REVIEW_COURSES = 'GET_REVIEW_COURSES';
export const GET_REVIEW_PROFS = 'GET_REVIEW_PROFS';
export const CLEAN_CURRENT_PROF = 'CLEAN_CURRENT_PROF';
export const SORT_PROF_UP = 'SORT_PROF_UP';
export const SORT_PROF_DOWN = 'SORT_PROF_DOWN';
